version: "3.8"

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,sqs
      - EAGER_SERVICE_LOADING=1
      - PROVIDER_OVERRIDE_S3=v2
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - .localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack_scripts/init.sh:/etc/localstack/init/ready.d/init.sh

  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.db:/var/lib/postgresql/data
