version: "3.8"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api.local
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - localstack
    networks:
      - app-network

  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification.local
    depends_on:
      - postgres
      - localstack
      - api
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,sqs
      - EAGER_SERVICE_LOADING=1
      - PROVIDER_OVERRIDE_S3=v2
    volumes:
      - .localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack_scripts/init.sh:/etc/localstack/init/ready.d/init.sh
    networks:
      - app-network

  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
